import SwiftUI

// MARK: - Today's Snapshot Scroll View v3

struct TodaysSnapshotScrollView: View {
    @Environment(\.dismiss) private var dismiss
    @State private var scrollOffset: CGFloat = 0
    @State private var initialY: CGFloat = 0
    
    // DEBUG: Toggle this to show/hide scroll position indicator
    private let showScrollDebug = true
    
    var body: some View {
        ZStack(alignment: .topLeading) {
            // Main Content Layer
            VStack(spacing: 0) {
            // Navigation Bar (fixed at top)
            FDSNavigationBarCentered(
                backAction: { dismiss() }
            )
            
            // Main Scrollable Content with Anchors
            ScrollViewReader { proxy in
                ScrollView {
                    VStack(spacing: 0) {
                        // Header Section
                        headerSection
                            .id("header")
                            .background(
                                GeometryReader { geo in
                                    Color.clear
                                        .onChange(of: geo.frame(in: .global).minY) { oldValue, newValue in
                                            // Set initial position once when first measured
                                            if initialY == 0 {
                                                initialY = newValue
                                            }
                                            // Calculate scroll: 0 at top, increases as you scroll down
                                            scrollOffset = max(0, initialY - newValue)
                                        }
                                }
                            )
                        
                        // Highlights Section
                        highlightsSection(proxy: proxy)
                            .id("highlights")
                        
                        // Red VStack Unit
                        VStack {
                            
                        }
                        .frame(width: 375, height: 300)
                        .background(Color.red)
                        
                        // Next sections will go here
                        // Story sections .id("story-1"), .id("story-2"), etc.
                        
                        // Temporary spacing
                        Color.clear
                            .frame(height: 500)
                    }
                }
            }
            
            // DEBUG: Scroll Position Indicator (Floating Layer)
            if showScrollDebug {
                Text("\(Int(scrollOffset))")
                    .font(.system(size: 14, weight: .bold, design: .monospaced))
                    .foregroundColor(.white)
                    .padding(.horizontal, 8)
                    .padding(.vertical, 4)
                    .background(Color.red.opacity(0.8))
                    .cornerRadius(6)
                    .padding(.leading, 12)
                    .padding(.top, 8)
                    .allowsHitTesting(false)
            }
        }
        .navigationBarHidden(true)
    }
    
    // MARK: - Header Section
    
    private var headerSection: some View {
        VStack(alignment: .leading, spacing: 0) {
            // Title + Meta Container with specific padding
            VStack(alignment: .leading, spacing: 0) {
                // Title
                Text("Today's snapshot")
                    .headline1EmphasizedTypography()
                    .foregroundStyle(Color("primaryText"))
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .padding(.top, 4)  // Inner top padding
                
                // 12px gap between title and meta
                Spacer().frame(height: 12)
                
                // Metadata
                Text(formattedDate + " · Generated by AI")
                    .meta2Typography()
                    .foregroundStyle(Color("secondaryText"))
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .padding(.bottom, 4)  // Inner bottom padding
            }
            .padding(.horizontal, 12)
            .padding(.top, 12)  // Outer top padding
            .padding(.bottom, 20)  // Outer bottom padding
            
            // 0px section divider (no padding)
            // Weather Action Chip
            HStack(spacing: 8) {
                FDSActionChip(
                    size: .medium,
                    label: "☀️72° Palo Alto",
                    isMenu: true,
                    action: {}
                )
                
                Spacer()
            }
            .padding(.horizontal, 12)
            .padding(.bottom, 12)
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(Color("surfaceBackground"))
    }
    
    // MARK: - Highlights Section
    
    private func highlightsSection(proxy: ScrollViewProxy) -> some View {
        // ListCellTable Container (gray background: F2F4F7)
        VStack(spacing: 0) {
            // White Card with list items
            VStack(spacing: 0) {
                // Unit Header: "Highlights" (has built-in padding: 12h, 20t, 8b)
                FDSUnitHeader(
                    headlineText: "Highlights",
                    hierarchyLevel: .level3
                )
                .padding(.top, 8)  // Additional 8px on top of built-in 20px = 28px total
                // FDSUnitHeader already has: 20px top, 8px bottom, 12px horizontal
                // Need 16px between header and first item: 8px (built-in) + 8px = 16px
                
                // Group Container (Items Container)
                VStack(spacing: 0) {
                    ForEach(highlightItems.indices, id: \.self) { index in
                        highlightListItem(item: highlightItems[index], index: index, proxy: proxy)
                    }
                }
                .padding(.top, 8)  // 8px (UnitHeader bottom) + 8px = 16px total
                .padding(.bottom, 8)
            }
            .background(Color("cardBackground"))  // White background
            .cornerRadius(8)
        }
        .padding(.top, 20)
        .padding(.bottom, 20)
        .padding(.horizontal, 12)
        .background(Color("bottomSheetBackgroundDeemphasized"))  // Gray background F2F4F7
    }
    
    // MARK: - Highlight List Item
    
    private func highlightListItem(item: HighlightItem, index: Int, proxy: ScrollViewProxy) -> some View {
        // Body Outer Container: 8px top/bottom, 0px left/right
        Button(action: {
            withAnimation {
                proxy.scrollTo("story-\(index + 1)", anchor: .top)
            }
        }) {
            // ContentRightAddon: 12px left/right, 0px top/bottom, 12px gap between children
            HStack(alignment: .center, spacing: 12) {
                // TextPairing: 4px top/bottom, 0px left/right, 2px gap, grow
                VStack(alignment: .leading, spacing: 2) {
                    // TextBlock: 15px font, 20px line-height
                    (Text(item.title)
                        .font(.body3Link)  // Body 3 Link (bold/semibold)
                    + Text(" ")
                    + Text(item.body)
                        .font(.body3))  // Body 3 (regular)
                        .foregroundColor(Color("primaryText"))
                }
                .padding(.vertical, 4)  // TextPairing padding
                .frame(maxWidth: .infinity, alignment: .leading)
                
                // ProfilePhotoCircle32Px
                Image(item.profileImage)
                    .resizable()
                    .scaledToFill()
                    .frame(width: 32, height: 32)
                    .clipShape(RoundedRectangle(cornerRadius: 8))
            }
            .padding(.horizontal, 12)  // ContentRightAddon horizontal padding
            .contentShape(Rectangle())
        }
        .padding(.vertical, 8)  // Body Outer Container vertical padding
        .buttonStyle(FDSPressedState(cornerRadius: 0))
    }
    
    // MARK: - Helpers
    
    private var formattedDate: String {
        let formatter = DateFormatter()
        formatter.dateFormat = "MMMM d"
        return formatter.string(from: Date())
    }
}

// MARK: - Highlight Item Model

struct HighlightItem {
    let title: String
    let body: String
    let profileImage: String
}

// MARK: - Sample Data

private let highlightItems: [HighlightItem] = [
    HighlightItem(
        title: "Pantone's Color of the Year",
        body: "for 2026, Cloud Dancer, emphasizes connection, adaptability, and optimism.",
        profileImage: "pantone_1"
    ),
    HighlightItem(
        title: "Jokic MVP race lead",
        body: "holds despite missed games, keeping league-wide debate intense through the midseason stretch.",
        profileImage: "jokic_1"
    ),
    HighlightItem(
        title: "Children Museum Winter Programs",
        body: "expansion adds new hands-on activities for toddlers and young children.",
        profileImage: "winter1"
    ),
    HighlightItem(
        title: "High protein toddler snacks",
        body: "can be easily upgraded using simple pantry additions recommended by dietitians.",
        profileImage: "ffmeal_1"
    ),
    HighlightItem(
        title: "Denver Restaurant Week Dates",
        body: "were announced, featuring prix-fixe menus at 300+ restaurants.",
        profileImage: "denver1"
    )
]

#Preview {
    NavigationStack {
        TodaysSnapshotScrollView()
    }
}
