import SwiftUI

struct TodaysSnapshotSnapView: View {
    @Environment(\.dismiss) private var dismiss
    @State private var currentIndex = 0
    
    private var formattedDate: String {
        let formatter = DateFormatter()
        formatter.dateFormat = "MMMM d"
        return formatter.string(from: Date())
    }
    
    var body: some View {
        GeometryReader { geometry in
            ZStack {
                // Background
                Color("bottomSheetBackgroundDeemphasized")
                    .ignoresSafeArea()
                
                VStack(spacing: 0) {
                    // Navigation Bar
                    HStack {
                        Button(action: { dismiss() }) {
                            Image("chevron-left-outline")
                                .resizable()
                                .renderingMode(.template)
                                .frame(width: 24, height: 24)
                                .foregroundColor(Color("primaryIcon"))
                        }
                        .padding(.leading, 12)
                        
                        Spacer()
                    }
                    .frame(height: 52)
                    .background(Color("surfaceBackground"))
                    
                    // Vertical Snapping ScrollView
                    ScrollViewReader { scrollProxy in
                        ScrollView(.vertical, showsIndicators: false) {
                            LazyVStack(spacing: 0) {
                                // Initial landing page
                                InitialSnapPage(
                                    formattedDate: formattedDate,
                                    currentIndex: $currentIndex,
                                    scrollProxy: scrollProxy,
                                    onExplore: {
                                        withAnimation(.easeInOut(duration: 0.4)) {
                                            currentIndex = 1
                                            scrollProxy.scrollTo(1, anchor: .top)
                                        }
                                    }
                                )
                                .frame(width: geometry.size.width, height: geometry.size.height - 52)
                                .id(0)
                                
                                // Full-screen snapshot cards
                                ForEach(Array(snapSnapshotItems.enumerated()), id: \.element.id) { index, item in
                                    FullScreenSnapCard(item: item)
                                        .frame(width: geometry.size.width, height: geometry.size.height - 52)
                                        .id(index + 1)
                                }
                            }
                            .scrollTargetLayout()
                        }
                        .scrollTargetBehavior(.paging)
                        .scrollIndicators(.hidden)
                    }
                }
            
            // White overlay mask at bottom to prevent peeking
            VStack {
                Spacer()
                Rectangle()
                    .fill(Color.white)
                    .frame(height: 40)
                    .offset(y: 20) // Offset to cover the bottom 60px area
                    .allowsHitTesting(false)
            }
            .ignoresSafeArea()
        }
        .hideFDSTabBar(true)
        .navigationBarHidden(true)
    }
    }
}

// MARK: - Initial Snap Page

struct InitialSnapPage: View {
    let formattedDate: String
    @Binding var currentIndex: Int
    let scrollProxy: ScrollViewProxy
    let onExplore: () -> Void
    
    var body: some View {
        ZStack {
            Color("bottomSheetBackgroundDeemphasized")
                .ignoresSafeArea()
            
            VStack(spacing: 0) {
                // Header Section
                VStack(alignment: .leading, spacing: 0) {
                    Text("Today's snapshot")
                        .headline1EmphasizedTypography()
                        .foregroundStyle(Color("primaryText"))
                        .frame(maxWidth: .infinity, alignment: .leading)
                    
                    Text(formattedDate + " · Generated by AI")
                        .meta2Typography()
                        .foregroundStyle(Color("secondaryText"))
                        .padding(.top, 12)
                }
                .padding(.horizontal, 12)
                .padding(.bottom, 20)
                .frame(maxWidth: .infinity, alignment: .leading)
                .background(Color("surfaceBackground"))
                
                // Action Chips
                HStack(spacing: 8) {
                    Button(action: {}) {
                        HStack(spacing: 4) {
                            Text("☀️72° Palo Alto")
                                .body4Typography()
                                .foregroundColor(Color("primaryText"))
                            
                            Image("triangle-down-filled")
                                .resizable()
                                .renderingMode(.template)
                                .frame(width: 12, height: 12)
                                .foregroundColor(Color("secondaryIcon"))
                        }
                        .padding(.horizontal, 12)
                        .padding(.vertical, 8)
                        .background(Color("wash"))
                        .cornerRadius(16)
                    }
                    
                    Button(action: {}) {
                        HStack(spacing: 4) {
                            Image("play-outline")
                                .resizable()
                                .renderingMode(.template)
                                .frame(width: 12, height: 12)
                                .foregroundColor(Color("secondaryIcon"))
                            
                            Text("5:30 listen")
                                .body4Typography()
                                .foregroundColor(Color("primaryText"))
                        }
                        .padding(.horizontal, 12)
                        .padding(.vertical, 8)
                        .background(Color("wash"))
                        .cornerRadius(16)
                    }
                    
                    Button(action: {}) {
                        HStack(spacing: 4) {
                            Image("gen-ai-star-filled")
                                .resizable()
                                .renderingMode(.template)
                                .frame(width: 12, height: 12)
                                .foregroundColor(Color("secondaryIcon"))
                            
                            Text("Ask AI")
                                .body4Typography()
                                .foregroundColor(Color("primaryText"))
                        }
                        .padding(.horizontal, 12)
                        .padding(.vertical, 8)
                        .background(Color("wash"))
                        .cornerRadius(16)
                    }
                    
                    Spacer()
                }
                .padding(.horizontal, 12)
                .padding(.bottom, 12)
                .background(Color("surfaceBackground"))
                
                // Scrollable card preview stack
                ScrollView {
                    VStack(spacing: 0) {
                        ForEach(Array(snapSnapshotItems.enumerated()), id: \.element.id) { index, item in
                            SnapCardPreview(item: item, index: index, onTap: {
                                withAnimation(.easeInOut(duration: 0.4)) {
                                    currentIndex = index + 1
                                    scrollProxy.scrollTo(index + 1, anchor: .top)
                                }
                            })
                            .padding(.horizontal, 12)
                            .padding(.top, 12)
                        }
                    }
                    .padding(.bottom, 100)
                }
            }
            
            // Floating Explore Button
            VStack {
                Spacer()
                
                Button(action: onExplore) {
                    ZStack {
                        Circle()
                            .fill(Color("cardBackground"))
                            .frame(width: 32, height: 32)
                            .shadow(color: Color.black.opacity(0.1), radius: 8, x: 0, y: 2)
                        
                        Image("arrow-down-filled")
                            .resizable()
                            .renderingMode(.template)
                            .frame(width: 16, height: 16)
                            .foregroundColor(Color("primaryText"))
                    }
                }
                .padding(.bottom, 30)
            }
        }
    }
}

// MARK: - Snap Card Preview (for initial page)

struct SnapCardPreview: View {
    let item: SnapshotItem
    let index: Int
    let onTap: () -> Void
    
    var body: some View {
        Button(action: onTap) {
            VStack(alignment: .leading, spacing: 0) {
                // Emoji + Headline
                HStack(alignment: .center, spacing: 8) {
                    Text(item.emoji)
                        .font(.system(size: 20))
                    
                    Text(item.detailTitle)
                        .headline4Typography()
                        .foregroundStyle(Color("primaryText"))
                        .fontWeight(.semibold)
                    
                    Spacer()
                }
                .padding(.horizontal, 12)
                .padding(.top, 12)
                .padding(.bottom, 8)
                
                // Body Text - truncated at 2 lines with "see more"
                (Text(item.summaryParagraph)
                    .foregroundColor(Color("primaryText"))
                + Text("... ")
                    .foregroundColor(Color("primaryText"))
                + Text("see more")
                    .foregroundColor(Color("secondaryText")))
                .body3Typography()
                .lineLimit(2)
                .multilineTextAlignment(.leading)
                .frame(maxWidth: .infinity, alignment: .leading)
                .padding(.horizontal, 12)
                .padding(.bottom, 12)
            }
            .background(Color("cardBackground"))
            .cornerRadius(8)
        }
        .buttonStyle(PlainButtonStyle())
    }
}

// MARK: - Full Screen Snap Card

struct FullScreenSnapCard: View {
    let item: SnapshotItem
    @State private var isExpanded = false
    
    var body: some View {
        ZStack {
            Color("surfaceBackground")
                .ignoresSafeArea()
            
            ScrollView {
                    VStack(alignment: .leading, spacing: 0) {
                        // Header with emoji + title + menu
                        HStack(alignment: .center, spacing: 0) {
                            SnapshotEmojiContainer(emoji: item.emoji, size: 28)
                            
                            Text(item.detailTitle)
                                .headline3EmphasizedTypography()
                                .foregroundStyle(Color("primaryText"))
                                .frame(maxWidth: .infinity, alignment: .leading)
                                .padding(.leading, 8)
                            
                            Button(action: {}) {
                                Image("dots-3-horizontal-outline")
                                    .resizable()
                                    .renderingMode(.template)
                                    .frame(width: 20, height: 20)
                                    .foregroundColor(Color("primaryIcon"))
                            }
                        }
                        .padding(.horizontal, 12)
                        .padding(.top, 12)
                        
                        // Summary paragraph with see more
                        Button(action: {
                            withAnimation {
                                isExpanded.toggle()
                            }
                        }) {
                            VStack(alignment: .leading, spacing: 0) {
                                if isExpanded {
                                    Text(item.summaryParagraph)
                                        .body3Typography()
                                        .foregroundStyle(Color("primaryText"))
                                        .frame(maxWidth: .infinity, alignment: .leading)
                                } else {
                                    (Text(item.summaryParagraph)
                                        .foregroundColor(Color("primaryText"))
                                    + Text("... ")
                                        .foregroundColor(Color("primaryText"))
                                    + Text("see more")
                                        .foregroundColor(Color("secondaryText")))
                                    .body3Typography()
                                    .lineLimit(2)
                                    .frame(maxWidth: .infinity, alignment: .leading)
                                }
                            }
                        }
                        .buttonStyle(PlainButtonStyle())
                        .padding(.horizontal, 12)
                        .padding(.top, 8)
                        
                        // Sources action chip (only when expanded)
                        if isExpanded {
                            HStack {
                                FDSActionChip(
                                    surface: .surface,
                                    type: .primary,
                                    size: .medium,
                                    label: "Sources",
                                    leftAddOn: nil,
                                    isMenu: false,
                                    isEmphasized: false,
                                    action: {}
                                )
                                
                                Spacer()
                            }
                            .padding(.horizontal, 12)
                            .padding(.top, 12)
                        }
                        
                        // "People are saying" section
                        Text("People are saying")
                            .headline4Typography()
                            .foregroundStyle(Color("primaryText"))
                            .padding(.horizontal, 12)
                            .padding(.top, 20)
                        
                        // 2-column post grid
                        SnapPostGrid(items: item.mediaItems)
                            .padding(.horizontal, 12)
                            .padding(.top, 8)
                        
                        // Thumbs up/down footer
                        HStack(spacing: 16) {
                            Button(action: {}) {
                                Image("hand-thumbs-up-outline")
                                    .resizable()
                                    .renderingMode(.template)
                                    .frame(width: 16, height: 16)
                                    .foregroundColor(Color("secondaryIcon"))
                            }
                            
                            Button(action: {}) {
                                Image("hand-thumbs-down-outline")
                                    .resizable()
                                    .renderingMode(.template)
                                    .frame(width: 16, height: 16)
                                    .foregroundColor(Color("secondaryIcon"))
                            }
                            
                            Spacer()
                        }
                        .padding(.horizontal, 12)
                        .padding(.top, 16)
                        .padding(.bottom, 20)
                    }
                }
            }
    }
}

// MARK: - Snap Post Grid

struct SnapPostGrid: View {
    let items: [MediaItem]
    
    var body: some View {
        LazyVGrid(
            columns: [
                GridItem(.flexible(), spacing: 8),
                GridItem(.flexible(), spacing: 8)
            ],
            spacing: 8
        ) {
            ForEach(Array(items.prefix(4).enumerated()), id: \.offset) { index, item in
                ResponsivePostCard(item: item, index: index)
            }
        }
    }
}

// MARK: - Responsive Post Card

struct ResponsivePostCard: View {
    let item: MediaItem
    let index: Int
    
    var body: some View {
        GeometryReader { geometry in
            ZStack(alignment: .topLeading) {
                // Full background image
                Image(item.imageName)
                    .resizable()
                    .scaledToFill()
                    .frame(width: geometry.size.width, height: geometry.size.height)
                    .clipped()
                
                // Header overlaid on top
                HStack(spacing: 8) {
                    Circle()
                        .fill(Color.white.opacity(0.9))
                        .frame(width: 20, height: 20)
                        .overlay(
                            Text("BT")
                                .font(.system(size: 10, weight: .semibold))
                                .foregroundColor(Color("primaryText"))
                        )
                    
                    Text("Becker Threads")
                        .font(.system(size: 13, weight: .semibold))
                        .foregroundColor(Color.white)
                        .kerning(-0.08)
                        .shadow(color: Color.black.opacity(0.3), radius: 2, x: 0, y: 1)
                    
                    Spacer()
                }
                .padding(.horizontal, 12)
                .padding(.top, 12)
            }
            .frame(width: geometry.size.width)
            .cornerRadius(12)
            .clipped()
        }
        .aspectRatio(0.7, contentMode: .fit)
    }
}

// MARK: - Data

private let snapSnapshotItems: [SnapshotItem] = [
    SnapshotItem(
        emoji: "🎨",
        headline: "for 2026, Cloud Dancer, emphasizes connection, adaptability, and optimism.",
        meta: "Read about Pantone's Color of the Year",
        detailTitle: "Pantone Color of the Year",
        summaryParagraph: "This year's selection signals a shift toward emotional grounding and softer visual language across design culture.",
        relatedPosts: [],
        profileImage: "pantone_1",
        mediaItems: [
            MediaItem(imageName: "pantone_1", aspectRatio: .portrait),
            MediaItem(imageName: "pantone_2", aspectRatio: .landscape),
            MediaItem(imageName: "pantone_3", aspectRatio: .square),
            MediaItem(imageName: "pantone_4", aspectRatio: .portrait)
        ]
    ),
    SnapshotItem(
        emoji: "🏀",
        headline: "Despite missing recent games, the Denver center remains the benchmark for MVP.",
        meta: "Latest NBA MVP Rankings",
        detailTitle: "Jokic MVP Race Lead",
        summaryParagraph: "Despite missing recent games, the Denver center remains the benchmark for MVP.",
        relatedPosts: [],
        profileImage: "jokic_1",
        mediaItems: [
            MediaItem(imageName: "jokic_1", aspectRatio: .portrait),
            MediaItem(imageName: "jokic_2", aspectRatio: .landscape),
            MediaItem(imageName: "jokic_3", aspectRatio: .square),
            MediaItem(imageName: "jokic_4", aspectRatio: .portrait)
        ]
    ),
    SnapshotItem(
        emoji: "🎭",
        headline: "New programming is giving families more indoor options during Denver's colder months.",
        meta: "Family Activities in Denver",
        detailTitle: "Children Museum Winter Programs",
        summaryParagraph: "New programming is giving families more indoor options during Denver's colder months.",
        relatedPosts: [],
        profileImage: "winter1",
        mediaItems: [
            MediaItem(imageName: "winter1", aspectRatio: .portrait),
            MediaItem(imageName: "winter2", aspectRatio: .landscape),
            MediaItem(imageName: "winter3", aspectRatio: .square),
            MediaItem(imageName: "winter1", aspectRatio: .portrait)
        ]
    ),
    SnapshotItem(
        emoji: "🥗",
        headline: "Dietitians say small pantry upgrades can meaningfully boost protein intake for kids.",
        meta: "Healthy Eating for Kids",
        detailTitle: "High-protein toddler snacks",
        summaryParagraph: "Dietitians say small pantry upgrades can meaningfully boost protein intake for kids.",
        relatedPosts: [],
        profileImage: "ffmeal_1",
        mediaItems: [
            MediaItem(imageName: "ffmeal_1", aspectRatio: .portrait),
            MediaItem(imageName: "ffmeal_2", aspectRatio: .landscape),
            MediaItem(imageName: "ffmeal_3", aspectRatio: .square),
            MediaItem(imageName: "ffmeal_4", aspectRatio: .portrait)
        ]
    ),
    SnapshotItem(
        emoji: "🍽️",
        headline: "The annual dining event returns with expanded participation and citywide prix-fixe menus.",
        meta: "Denver Food Events",
        detailTitle: "Denver Restaurant Week",
        summaryParagraph: "The annual dining event returns with expanded participation and citywide prix-fixe menus.",
        relatedPosts: [],
        profileImage: "denver1",
        mediaItems: [
            MediaItem(imageName: "denver1", aspectRatio: .portrait),
            MediaItem(imageName: "denver2", aspectRatio: .landscape),
            MediaItem(imageName: "denver3", aspectRatio: .square),
            MediaItem(imageName: "denver1", aspectRatio: .portrait)
        ]
    )
]

#Preview {
    TodaysSnapshotSnapView()
}
