import SwiftUI

// MARK: - Today's Snapshot Scroll View v3

struct TodaysSnapshotScrollView: View {
    @Environment(\.dismiss) private var dismiss
    
    var body: some View {
        VStack(spacing: 0) {
            // Navigation Bar (fixed at top)
            FDSNavigationBarCentered(
                backAction: { dismiss() }
            )
            
            // Main Scrollable Content with Anchors
            ScrollViewReader { proxy in
                ScrollView {
                    VStack(spacing: 0) {
                        // Header Section
                        headerSection
                            .id("header")
                        
                        // Next sections will go here
                        // Highlights section .id("highlights")
                        // Story sections .id("story-1"), .id("story-2"), etc.
                        
                        // Temporary spacing
                        Color.clear
                            .frame(height: 500)
                    }
                }
            }
        }
        .navigationBarHidden(true)
    }
    
    // MARK: - Header Section
    
    private var headerSection: some View {
        VStack(alignment: .leading, spacing: 0) {
            // Title + Meta Container with specific padding
            VStack(alignment: .leading, spacing: 0) {
                // Title
                Text("Today's snapshot")
                    .headline1EmphasizedTypography()
                    .foregroundStyle(Color("primaryText"))
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .padding(.top, 4)  // Inner top padding
                
                // 12px gap between title and meta
                Spacer().frame(height: 12)
                
                // Metadata
                Text(formattedDate + " · Generated by AI")
                    .meta2Typography()
                    .foregroundStyle(Color("secondaryText"))
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .padding(.bottom, 4)  // Inner bottom padding
            }
            .padding(.horizontal, 12)
            .padding(.top, 12)  // Outer top padding
            .padding(.bottom, 20)  // Outer bottom padding
            
            // 0px section divider (no padding)
            // Weather Action Chip
            HStack(spacing: 8) {
                FDSActionChip(
                    size: .medium,
                    label: "☀️72° Palo Alto",
                    isMenu: true,
                    action: {}
                )
                
                Spacer()
            }
            .padding(.horizontal, 12)
            .padding(.bottom, 12)
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(Color("surfaceBackground"))
    }
    
    // MARK: - Helpers
    
    private var formattedDate: String {
        let formatter = DateFormatter()
        formatter.dateFormat = "MMMM d"
        return formatter.string(from: Date())
    }
}

#Preview {
    NavigationStack {
        TodaysSnapshotScrollView()
    }
}
